# Automatically merge Dependabot PRs when version comparison is within the range
# that is configured in .github/auto-merge.yml

name: Auto-Merge Dependabot PRs
permissions:
  contents: write
  pull-requests: write
on:
  pull_request_target:

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if PR should be auto-merged
        uses: iobroker-bot-orga/action-automerge-dependabot@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
